import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowRight, MessageCircleMore } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { AskGurujiButton } from "@/components/ai/AskGurujiButton";
import { PriceBadge } from "@/components/ui/Badge";
import { VedicSymbol } from "@/components/icons/VedicSymbol";
import { getServiceSymbol } from "@/lib/presentation/vedic-symbols";
import { cn } from "@/lib/utils";
export function ServiceCard({ service }) {
    return (_jsxs("article", { className: "group relative flex h-full flex-col overflow-hidden rounded-3xl border border-gold/20 bg-surface/60 p-6 transition-all duration-300 hover:-translate-y-1.5 hover:border-gold/50 hover:shadow-[var(--shadow-glow-gold)]", children: [_jsx("div", { className: cn("pointer-events-none absolute -right-16 -top-16 h-40 w-40 rounded-full bg-gradient-to-br opacity-40 blur-3xl transition-opacity duration-300 group-hover:opacity-70", service.gradient) }), _jsxs("div", { className: "relative flex items-start justify-between gap-3", children: [_jsx("div", { className: cn("grid h-16 w-16 place-items-center rounded-full border border-gold/40 bg-gradient-to-br text-gold-deep shadow-[inset_0_0_0_5px_rgba(193,145,47,0.08)]", service.gradient), title: service.icon, children: _jsx(VedicSymbol, { kind: getServiceSymbol(service.slug), size: "lg", strokeWidth: 1.6 }) }), _jsx(PriceBadge, { price: service.price, discountPrice: service.discountPrice })] }), _jsx("h3", { className: "relative mt-5 font-serif text-xl text-ink", children: _jsx("a", { href: `/services/${service.slug}`, className: "after:absolute after:inset-0", children: service.title }) }), _jsx("p", { className: "relative mt-2 flex-1 text-sm leading-relaxed text-muted", children: service.shortDescription }), _jsxs("div", { className: "relative z-10 mt-6 grid gap-2 grid-cols-2", children: [_jsxs(Button, { href: `/services/${service.slug}`, variant: "primary", size: "md", className: "w-full", children: ["Book", _jsx(ArrowRight, { className: "h-4 w-4" })] }), _jsxs(AskGurujiButton, { serviceTitle: service.title, className: "w-full justify-center rounded-xl border border-gold/40 bg-[#3d1822]/80 text-[#ffe2a1] text-xs h-10 px-3 hover:bg-[#52202f]", children: [_jsx(MessageCircleMore, { className: "h-3.5 w-3.5" }), " Ask Guruji"] })] }), _jsx("span", { "aria-hidden": true, className: "pointer-events-none absolute inset-0 z-0 -translate-x-full bg-gradient-to-r from-transparent via-white/15 to-transparent transition-transform duration-1000 ease-out group-hover:translate-x-full" })] }));
}
