import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CheckCircle2 } from "lucide-react";
import { Section } from "@/components/ui/Section";
import { Reveal } from "@/components/effects/Reveal";
import { Button } from "@/components/ui/Button";
import { StarField } from "@/components/effects/StarField";
import { gurujiProfile, homeStats } from "@/lib/data/content";
export function AboutPreview() {
    return (_jsx(Section, { children: _jsxs("div", { className: "grid items-center gap-12 lg:grid-cols-2", children: [_jsx(Reveal, { children: _jsxs("div", { className: "relative", children: [_jsx("div", { className: "divine-glow absolute -inset-4 rounded-[2rem] bg-gradient-to-br from-saffron/20 to-gold/15 blur-2xl" }), _jsxs("div", { className: "glass-card relative overflow-hidden rounded-[2rem] p-8", children: [_jsx(StarField, { count: 30, seed: 5 }), _jsxs("div", { className: "relative flex flex-col items-center text-center", children: [_jsx("div", { className: "grid h-28 w-28 place-items-center rounded-full bg-gradient-to-br from-purple-700 to-saffron-deep text-5xl ring-2 ring-gold/40", children: "\uD83D\uDD49\uFE0F" }), _jsx("h3", { className: "mt-5 font-serif text-2xl text-ink", children: gurujiProfile.name }), _jsxs("p", { className: "mt-1 text-sm text-gold-light", children: ["Vedic Astrologer \u00B7 ", gurujiProfile.experience] }), _jsx("div", { className: "mt-6 grid w-full grid-cols-2 gap-3", children: homeStats.slice(0, 4).map((s) => (_jsxs("div", { className: "rounded-2xl border border-gold/15 bg-[#b67a1b]/[0.035] px-3 py-3", children: [_jsx("div", { className: "font-serif text-xl text-gold-light", children: s.value }), _jsx("div", { className: "text-[0.65rem] uppercase tracking-wide text-faint", children: s.label })] }, s.label))) })] })] })] }) }), _jsxs("div", { children: [_jsx(Reveal, { children: _jsx("span", { className: "text-xs font-semibold uppercase tracking-[0.28em] text-gold", children: "About Guruji" }) }), _jsx(Reveal, { delay: 0.06, children: _jsxs("h2", { className: "mt-3 font-serif text-3xl text-ink sm:text-4xl", children: ["About ", gurujiProfile.name] }) }), _jsx(Reveal, { delay: 0.12, children: _jsx("p", { className: "mt-4 leading-relaxed text-muted", children: gurujiProfile.longBio }) }), _jsx(Reveal, { delay: 0.18, children: _jsx("ul", { className: "mt-6 grid grid-cols-1 gap-2.5 sm:grid-cols-2", children: gurujiProfile.specialization.slice(0, 6).map((sp) => (_jsxs("li", { className: "flex items-center gap-2 text-sm text-muted", children: [_jsx(CheckCircle2, { className: "h-4 w-4 shrink-0 text-gold" }), sp] }, sp))) }) }), _jsx(Reveal, { delay: 0.24, children: _jsxs("div", { className: "mt-8 flex flex-wrap gap-3", children: [_jsx(Button, { href: "/about-us", variant: "primary", size: "lg", children: "Read More" }), _jsx(Button, { href: "/chat-with-guruji", variant: "gold", size: "lg", children: "Chat with Guruji" })] }) })] })] }) }));
}
